import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          style={{
            background: 'url("/hero-img.jpg")',
            width: "100%",
            height: "400px",
            backgroundSize: "cover",
            backgroundPosition: "bottom",
          }}
        >
          <h1>Sustainable growth for everyone</h1>
        </div>

        <p>
          Here are some shortcuts to our internal systems. Each system will need
          you to sign in with your company issued email and password.
        </p>
        <div className={styles.grid}>
          <Link href="/drive">
            <a className={styles.card}>
              <h2>File Drive &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>

          <Link href="/employees">
            <a className={styles.card}>
              <h2>Employees &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
          </Link>

          <Link href="/systemsAndTools">
            <a className={styles.card}>
              <h2>Systems & Tools &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
